version: '3.2'
services:
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JENKINS_HOME: /opt/jenkins
    ports:
      - 4444:4444
    volumes:
      - ./:/opt/data
      - ./docker/datas/jenkins:/opt/jenkins
    command: java -jar /opt/jenkins/jenkins.war --httpPort=4444
