name: MinecraftLog
version: 0.1
description: Logger for Minecraft
author: René Majewski (TerraGermany)
website: http://www.rene-majewski.de
main: de.rene_majewski.rm_plugin.MinecraftLog

commands:
  minecraftlog:
    description: Reload the config.
    usage : /<command> config reload
    permission: minecraftlog.admin.reload
    aliases: [ml]
