name: RM-Plugin
version: 0.1
description: A plugin thats logs and include some commands and functions for my Minecraft server.
author: René Majewski (TerraGermany)
website: http://www.rene-majewski.de
main: de.rene_majewski.rm_plugin.RMPlugin

commands:
  rmplugin:
    description: Reload the config.
    usage : /<command> config reload
    permission: rmplugin.admin.reload
    aliases: [rml]
