CREATE TABLE IF NOT EXISTS `&log_block` (
  `id` BIGINT(20) AUTO_INCREMENT,
  `block_id` BIGINT(20) NOT NULL DEFAULT -1,
  `player_id` BIGINT(20) NOT NULL DEFAULT -1,
  `world_id` BIGINT(20) NOT NULL DEFAULT -1,
  `x` INT(11) NOT NULL,
  `y` INT(11) NOT NULL,
  `z` INT(11) NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` TINYINT(3) DEFAULT 0,
  PRIMARY KEY(`id`)
) CHARACTER SET utf8 COLLATE utf8_unicode_ci;