CREATE TABLE IF NOT EXISTS `&log_world_change` (
  `id` BIGINT(20) AUTO_INCREMENT,
  `player_id` BIGINT(20) NOT NULL DEFAULT -1,
  `world_id` BIGINT(20) NOT NULL DEFAULT -1,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(`id`)
) CHARACTER SET utf8 COLLATE utf8_unicode_ci;