CREATE TABLE IF NOT EXISTS `&log_loggin` (
  `id` BIGINT(20) AUTO_INCREMENT,
  `player_id` BIGINT(20) NOT NULL,
  `time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(2) DEFAULT 0,
  PRIMARY KEY(`id`)
)CHARACTER SET utf8 COLLATE utf8_unicode_ci;